[tool.poetry]
name = "pychat"
version = "0.1.0"
description = ""
authors = ["Critiek <jamesvsomeren@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
textual-dev = "^1.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
